@dotnet_chat_rag_HostAddress = http://localhost:5080

GET {{dotnet_chat_rag_HostAddress}}/weatherforecast/
Accept: application/json

### Ask gpt a question


### Chat/ask
POST {{dotnet_chat_rag_HostAddress}}/api/chat/ask
Content-Type: application/json

{
  "question": "What is java?"
}